### PR TITLE
Use same test config for react, add Jest

### PR DESCRIPTION
**Pull request by petrhanak**

### CODE REVIEW

**Review by robertrossmann — CHANGES_REQUESTED** [review]
If you remove the `jest` part I will merge this. 😄 I am even considering removing `mocha: true` from the config, to keep this framework-agnostic.

**Comment by petrhanak** [comment]
@robertrossmann the problem is, after removing jest configuration becomes more complicated. I would rather add `jasmine` to we cover all testing framework environments supported by eslint and leave it that way. I did this so developers don't have to setup their eslint config when writing test while you suggest doing exact opposite - forcing them to configure even it will either jest or mocha anyway.

**Comment by petrhanak** [comment]
Or maybe we could make new rule from this - something like `@strv/javascript/environments/jest`

**Comment by robertrossmann** [comment]
Merged via ca112ef...ab3ce22 without enabling `jest` and `mocha` env vars. I understand the reasoning why having them all enabled would save developers from having to configure the env themselves but the problem is that suddenly your linter would consider some variables as being defined even though they are not.

To remedy the situation somewhat, I have exposed the glob patterns from the module - below is an example usage.

```js
import * as globs from '@strv/eslint-config-javascript/globs'
const globs = require('@strv/eslint-config-javascript/globs')

module.exports = {
  overrides: [{
    files: globs.test,
    env: {
      jest: true
    }
  }]
}
```

**Pull request closed without merging**
