### PR TITLE
Proposal: Require space after "!"

### PR DESCRIPTION
**Pull request by robertrossmann**
This was my intention for the very beginning, unfortunately ESLint did not such configuration without forcing us to write weird code in other places.
#### Current style:

``` js
if (!true) {
  // do stuff
}
const isTrue = !true
```
#### Proposed style:

``` js
if (! true) { // <-- extra space
  // do stuff
}
const isTrue = ! true // <-- extra space
```

Violations of this rule will be automatically fixable in your codebase if this proposal is accepted, so 0 total work required on your behalf.

**Please vote with 👍 if you prefer the newly proposed coding style or 👎 if you prefer to keep the current.**

### CODE REVIEW

**Comment by TomasHubelbauer** [comment]
This is extremely uncommon and will be familiar to no one. Why do you propose this rule? What benefit would you like to see realized by honoring this rule consistently?

**Comment by ondrejstocek** [comment]
For consistency you should consider all expressions with `!` not just those in if statement.
What about this
`const result = ! boolValue`
`if (someValue || ! otherValue) ...`

And double usage?
`return ! ! value`

It looks really wierd.

**Comment by capaj** [comment]
@TomasHubelbauer I think the reason is to make it more obvious, when flipping Boolean values in the if statement. While I think it would increase readability slightly, it would make it more annoying to type. I think it is better to just set a different colour for operators in your editor.

**Comment by robertrossmann** [comment]
Having a space after `!` kinda increases readability for me when negating expressions, so that would be the reason for proposing this. :smile:

**Comment by robertrossmann** [comment]
@ondrejstocek This rule enforces spacing after unary negation operator everywhere.

`!!` is discouraged already, you should use `Boolean(expression)` instead if you want to convert a value to explicit boolean.

**Comment by robertrossmann** [comment]
Well, did not expect that there is only one person using this coding style. :) Thanks for your feedback, this will stay unchanged!

**Pull request closed without merging**
