### PR TITLE
Allow to use module

### PR DESCRIPTION
**Pull request by petrhanak**
for cases like HMR (https://webpack.js.org/guides/hot-module-replacement/)
```
if (module.hot) {
  ...
}
```
used by almost every project

### CODE REVIEW

**Comment by robertrossmann** [comment]
Hey! I don't think this is a good idea (enabling commonjs for react code) for several reasons:

- React code usually runs on browsers (SSR being an exception, of course) where commonjs module system is not available
- React code usually prefers ES2015 modules over commonjs module system and it is generally discouraged to mix them together in a single file
- It seems like an overkill to enable the whole commonjs environment just to fix a `module is not defined` error
- HMR is an optional feature of webpack - I would like to not favour specific development approaches in a React stylesheet
- This seems like something that should (and can) be easily fixed in userland eslint configuration or directly in the file accessing `module` (see [configuring globals](https://eslint.org/docs/user-guide/configuring#specifying-globals) docs).

**Comment by petrhanak** [comment]
First of all, in browser neither es6 or commonjs is available, but with webpack we can use them. It's not only about HMR and `module.hot`, but also `module.exports`, `require` etc. With commonjs enabled we will more closely match actual environment. Currently the error says the `module is not defined` - which is wrong and confusing, `module` is there.

If we really want to restrict using commonjs modules, we should do it through `import/no-commonjs` rule (https://github.com/benmosher/eslint-plugin-import/blob/HEAD/docs/rules/no-commonjs.md).

But again there are cases where we need commonjs.

*conditional loading of libraries:*
```
if(isDevelopment()){
  const someDevTool = require('some-development-tool')
  someDevTool.doMagic()
}
```

```
if (isProduction()) {
  const runtime = require('offline-plugin/runtime')
  runtime.install()
}
```

*computed export:*
```
module.exports = getExportObject()
```

I don't think we should enable `import/no-commonjs` rule, I was thinking about putting `warn` in `environments/react/optional`, but not even warning would make sense. There is no scenario where developer uses comonjs in accident. It's not like forgetting to remove `console.log` or unused import. If developer uses commonjs, there is probably very good reason for it and he is aware what he is doing.

**Comment by robertrossmann** [comment]
I still don't think this to be a good idea. For example

```js
import stuff from 'stuff'
const other = require('other')
// or
module.exports = {}
```

is simply not a valid ES module nor is it a valid commonJS module. The problem is that natively, ES modules do not implement commonJS interfaces and commonJS modules cannot import ES modules. This kind of hybrid is only possible due to Babel/webpack compiling ES modules down to commonJS syntax. However, there are no plans to support this kind of interoperability neither in browsers nor in Node.js in the future.

So even though you currently can check for `module.hot` inside an ES module, this is not optimal and enabling the commonjs runtime for React apps goes against what some or most people would expect.

As you point out, given that

- You want to use HMR
- You understand the implications of mixing ES modules with CommonJS modules

it is absolutely fine to enable commonjs runtime in your project's configuration, but I am strongly against enabling commonjs for files which are treated as ES modules.

> It is true that loading a module during runtime is currently impossible with ES modules and needs `require`. This sucks. But it is still possible to solve that by moving dynamic requires into a classic script file and load that file with `node --require ...` or use the dynamic imports plugin for [babel](https://github.com/airbnb/babel-plugin-dynamic-import-node)/webpack.

**Comment by petrhanak** [comment]
I get it, this would mean locking project to one vendor - webpack. Rollup for example provides support for ES6 modules only. Closing then, it's not a good idea.

**Pull request closed without merging**
